# Generated by Django 6.0.3 on 2026-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
