# Generated by Django 6.0.3 on 2026-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_full_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('P', 'Paused'), ('A', 'Active'), ('C', 'Cancelled')], default='A', max_length=1),
        ),
    ]
