# Generated by Django 6.0.3 on 2026-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='frequency',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='frequency',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grind',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_locked',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The 10% discounted price locked in at purchase', max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
